#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RssReaderForms.Android.Resource", IsApplication=true)]

namespace RssReaderForms.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::RssReaderForms.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::RssReaderForms.Android.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::RssReaderForms.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::RssReaderForms.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int carrot = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int favorite_grey = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int favorite_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gray = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int heart = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int heart_shape = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_accept = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_favorite = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_new = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_refresh = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_share = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int image_button_states = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int infav = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int not_favorite_grey = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int not_favorite_white = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rss_icons = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shape_opacity = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int shape_select = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Splash = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int ApplicationName = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Hello = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Share = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int ActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int SplashScreen = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
